bind s choose-tree -F '#{?window_format,#{window_name},}' -NZw
bind w choose-tree -F '#{?window_format,#{window_name},}' -NZw
set -g automatic-rename on
set -g automatic-rename-format 'new'
set -g default-command '/usr/bin/bash --init-file "$ZONE/.bashrc"'
set -g default-terminal 'tmux-256color'
set -g escape-time 10
set -g focus-events on
set -g mouse on
set -g pane-active-border-style "bold,fg=blue"
set -g pane-border-style "bold,fg=blue"
set -g status-left "#S "
set -g status-right ""
set -g status-style "bg=terminal,fg=blue"
set -g terminal-overrides ',*:RGB'
set -g window-status-bell-style none
set -g window-status-current-format "#W"
set -g window-status-current-style "bold,fg=blue"
set -g window-status-format "#W"
set -g window-status-style "fg=brightblack"
